version: '3.8'

services:
  payload:
    container_name: lms
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - '3000'
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=app.fysite.id
      - LETSENCRYPT_HOST=app.fysite.id
      - LETSENCRYPT_EMAIL=testedprojected@gmail.com
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - nginx-proxy

  postgres:
    container_name: psql
    image: postgres:latest
    restart: unless-stopped
    env_file:
      - .env.db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true

volumes:
  pgdata:
