services:
  payload:
    container_name: lms
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - '3000'
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - nginx-proxy
    environment:
      - VIRTUAL_HOST=app.fysite.id
      - LETSENCRYPT_HOST=app.fysite.id
      - LETSENCRYPT_EMAIL=testedprojected@gmail.com

  postgres:
    container_name: psql
    image: postgres:15
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env.db
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true

volumes:
  pgdata:
