version: '3'

services:
  payload:
    container_name: lms
    image: node:18-alpine
    expose:
      - '3000'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "corepack enable && corepack prepare pnpm@latest --activate && pnpm install && pnpm start"
    depends_on:
      - postgres
    env_file:
      - .env

    environment:
      - VIRTUAL_HOST=app.fysite.id
      - LETSENCRYPT_HOST=app.fysite.id
      - LETSENCRYPT_EMAIL=testedprojected@gmail.com
    networks:
      - nginx-proxy

  postgres:
    restart: always
    container_name: psql
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env.db
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true

volumes:
  pgdata:
  node_modules:
